name: backend-ci

on:
  push:
    branches: [ maestros ]
  pull_request:
    branches: [ maestros ]
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 */5 * *'

jobs:
  backend-ci-app:
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: deploy the project
      run: sh docker-run.sh
      